# -*- coding: utf-8 -*-
"""user_input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFDuTC2g5fs1KiVEoFH4XKnm8IxuDTrX
"""

# Asking for user's name
name = input("What is your name? ")

# Asking for user's age
age = input("How old are you? ")

# Asking for user's location
location = input("Where do you live? ")

# Printing personalized message
print(f"Hello {name}, you are {age} years old and you live at {location}.")

